# GitHub action to build repos that are dependent on this library
name: Build Dependent Repos

on: 
  release:
    types: [published,edited]
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  build-dependent-repos:
    strategy:
      matrix:
        include:
          - name: Trigger build on MSP430TempSensorWithDisplay
            repo: MSP430TempSensorWithDisplay
          - name: Trigger build on LCD_SharpBoosterPack_SPI
            repo: LCD_SharpBoosterPack_SPI

    name: call-compile-sketches-workflow
    uses: Andy4495/.github/.github/workflows/build-dependent-repos.yml@main
    with:
      message: ${{ inputs.message }}
      repo-name: ${{ matrix.repo }}
    secrets: inherit
            